---
- name: Configure Nest API credentials.
  template:
    src: templates/nest_api.j2
    dest: "/home/{{ temperature_monitor_user }}/.nest_api"
    owner: "{{ temperature_monitor_user }}"
  when: nest_access_token != ''

- name: Configure Weather Underground credentials.
  template:
    src: templates/wu_api.j2
    dest: "/home/{{ temperature_monitor_user }}/.wu_api"
    owner: "{{ temperature_monitor_user }}"
  when: wu_api_key != ''

- name: Ensure cron job exists for Nest temperatures.
  cron:
    name: "Check Nest Thermostat temperatures"
    job: ". /home/{{ temperature_monitor_user }}/.wu_api; python {{ temperature_monitor_dir }}/scripts/outdoor-temps-wu.py > /dev/null 2>&1"
    user: "{{ temperature_monitor_user }}"
  when: nest_access_token != ''

- name: Ensure cron job exists for Weather Underground temperatures.
  cron:
    name: "Check Weather Underground temperatures"
    job: ". /home/{{ temperature_monitor_user }}/.nest_api; python {{ temperature_monitor_dir }}/scripts/nest-temps.py > /dev/null 2>&1"
    user: "{{ temperature_monitor_user }}"
  when: wu_api_key != ''
