---
- hosts: remotes

  vars_files:
    - ../../config/config.yml

  roles: []

  tasks:
    - name: Install dependencies for Python temperature scripts.
      apt: "name={{ item }} state=present"
      with_items:
        - python-pip
        - python-dev

    - name: Ensure the temperature-monitor repository is present.
      git:
        repo: https://github.com/geerlingguy/temperature-monitor.git
        dest: "{{ temperature_monitor_dir }}"
        update: yes
      when: deploy_target_is_pi

    - name: Install required Python libraries with pip.
      pip: "requirements={{ temperature_monitor_dir }}/scripts/requirements.txt"

    - name: Configure the settings file (temps.conf).
      template:
        src: ../master/templates/temps.conf.j2
        dest: "{{ temperature_monitor_dir }}/scripts/temps.conf"
        mode: 0644

    # TODO
    - name: Ensure the pi-temps.py script is active.
      command: true
      # command: "nohup python scripts/pi-temps.py > /dev/null 2>&1 &"
