---
- hosts: remotes
  sudo: yes

  vars_files:
    - ../../config/config.yml

  pre_tasks:
    - name: Ensure apt cache is updated.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - geerlingguy.git

  tasks:
    - name: Install dependencies for Python temperature scripts.
      apt: "name={{ item }} state=present"
      with_items:
        - python-pip
        - python-dev

    - name: Clean up bad Python requests package so pip works.
      shell: "rm -rf /usr/local/lib/python2.7/dist-packages/requests*"
      changed_when: false

    - name: Ensure the temperature-monitor repository is present.
      git:
        repo: https://github.com/geerlingguy/temperature-monitor.git
        dest: "{{ temperature_monitor_dir }}"
        update: yes
      become: true
      become_user: "{{ temperature_monitor_user }}"
      when: deploy_target_is_pi
      notify: restart pi-temps

    - name: Install required Python libraries with pip.
      pip: "requirements={{ temperature_monitor_dir }}/scripts/requirements.txt"

    - name: Configure the settings file (temps.conf).
      template:
        src: ../master/templates/temps.conf.j2
        dest: "{{ temperature_monitor_dir }}/scripts/temps.conf"
        mode: 0644
      notify: restart pi-temps

    - name: Configure the init file.
      template:
        src: templates/pi-temps-init.j2
        dest: "/etc/init.d/pi-temps"
        mode: 0755
      notify: restart pi-temps

    - name: Ensure the pi-temps service is active and enabled on boot.
      service: name=pi-temps state=started enabled=yes

  handlers:
    - name: restart pi-temps
      service: name=pi-temps state=restarted
